#!/bin/bash
OUTFILE='Zaphod.out'
RRIO_IPADDRESS='10.20.59.2'
if [ "$1" = "build" ];then
  cd src && make
elif [ "$1" = "clean" ];then
  cd src&&make clean
elif [ "$1" = "buildclean" ];then
  cd src&&make clean;make
elif [ "$1" = "deploy" ];then
  cd bin&&wput $OUTFILE ftp://frc:frc@10.20.59.2/ni-rt/system/FRC_UserProgram.out
fi
